### PR TITLE
remove copyright message, fixes #282

### LINKED ISSUE #282: "Copyright All rights reserved" footer
The site has a footer _"Copyright © 2016 MapRoulette Version 2.0.2. All rights reserved."_

Who is reserving all rights of what? The version number would imply we're talking about the software, but the maproulette software is Apache Licensed (As with any open source license technically it's copyrighted yes, but it's specifically _not_ "all rights reserved")

So unless I'm misunderstanding, the footer would be better just saying "MapRoulette Version 2.0.2. (source code)" (link to github)

### PR DESCRIPTION
**Pull request by mvexel**

### CODE REVIEW

**Comment by mvexel** [comment]
It looks like this now: 

screenshot 2017-03-09 10 26 53

**Comment by mvexel** [comment]
I also removed the 'link' around the MapRoulette name which did nothing.

**Comment by nebulon42** [comment]
For messages.de it could be `footer.getintouch=Kontaktieren Sie uns`. While `uns` means the plural form (literally Contact us) you could also use `mich` if it would be only you that receives the mails.

**Comment by mvexel** [comment]
`uns` us fine :)

**Pull request merged**
