### PR TITLE
Create GIST index on tasks location column

### PR DESCRIPTION
**Pull request by nrotstan**
* Add evolution ensuring that GIST index is created on tasks `location` column

### CODE REVIEW

**Comment by nrotstan** [comment]
One downside to modifying an early evolution is that play servers in development mode will want to execute the downs all the way back and then re-apply the ups, potentially causing data loss for the unwary. I'm happy to resubmit this as a new evolution to avoid that, if desired.

**Comment by mgcuthbert** [comment]
Actually as I looked at the code, I was like "no I don't want to deal with that". So I think we need to make it evolution 71 and I will run the index in the background for this release. And then 71 will run in the next release but because the index already exists it won't do anything.

**Review by mgcuthbert — CHANGES_REQUESTED** [review]
Create index in evolution 71, so that it is available for the next release.

**Comment by nrotstan** [comment]
I've updated this PR to include a new 71.sql evolution instead of modifying the 1.sql evolution

**Pull request merged**
